(function($){"use strict";function handlePreloader(){if($('.preloader').length){$('.preloader').delay(200).fadeOut(500);}}
function headerStyle(){if($('.main-header').length){var windowpos=$(window).scrollTop();var siteHeader=$('.main-header');var scrollLink=$('.scroll-to-top');if(windowpos>=200){siteHeader.addClass('fixed-header');scrollLink.fadeIn(300);}else{siteHeader.removeClass('fixed-header');scrollLink.fadeOut(300);}}}
headerStyle();if($('.main-header li.dropdown ul').length){$('.main-header li.dropdown').append('<div class="dropdown-btn"><span class="fa fa-angle-down"></span></div>');$('.main-header li.dropdown .dropdown-btn').on('click',function(){$(this).prev('ul').slideToggle(500);});$('.main-header .navigation li.dropdown > a').on('click',function(e){$(this).next('ul').slideToggle(500);});}
if($('.tabs-box').length){$('.tabs-box .tab-buttons .tab-btn').on('click',function(e){e.preventDefault();var target=$($(this).attr('data-tab'));if($(target).is(':visible')){return false;}else{target.parents('.tabs-box').find('.tab-buttons').find('.tab-btn').removeClass('active-btn');$(this).addClass('active-btn');target.parents('.tabs-box').find('.tabs-content').find('.tab').fadeOut(0);target.parents('.tabs-box').find('.tabs-content').find('.tab').removeClass('active-tab');$(target).fadeIn(300);$(target).addClass('active-tab');}});}
if($('.project-tab').length){$('.project-tab .product-tab-btns .p-tab-btn').on('click',function(e){e.preventDefault();var target=$($(this).attr('data-tab'));if($(target).hasClass('actve-tab')){return false;}else{$('.project-tab .product-tab-btns .p-tab-btn').removeClass('active-btn');$(this).addClass('active-btn');$('.project-tab .p-tabs-content .p-tab').removeClass('active-tab');$(target).addClass('active-tab');}});}
if($('.custom-scroll').length){$('.custom-scroll').mCustomScrollbar();}
if($('.progress-line').length){$('.progress-line').appear(function(){var el=$(this);var percent=el.data('width');$(el).css('width',percent+'%');},{accY:0});}
if($('.count-box').length){$('.count-box').appear(function(){var $t=$(this),n=$t.find(".count-text").attr("data-stop"),r=parseInt($t.find(".count-text").attr("data-speed"),10);if(!$t.hasClass("counted")){$t.addClass("counted");$({countNum:$t.find(".count-text").text()}).animate({countNum:n},{duration:r,easing:"linear",step:function(){$t.find(".count-text").text(Math.floor(this.countNum));},complete:function(){$t.find(".count-text").text(this.countNum);}});}},{accY:0});}
$(window).on("load resize",function(e){if($(window).width()>981){$("#sticky-rightbar").insertAfter("#main-navigation");}});$(window).on("load resize",function(e){if($(window).width()<980){$("#sticky-rightbar").insertAfter(".primary-nav");}});$('#sticky-rightbar ul > li').hover(function(){var wWidth=$(window).width();if(wWidth>981){$(this).toggleClass('selected').siblings().removeClass('selected');}});$('#sticky-rightbar ul > li a').click(function(){var wWidth=$(window).width();if(wWidth<981){$("#main-navigation").removeClass('active');$("#overlay").removeClass('active');}});$('.floating-icons').mouseover(function(){$(this).stop().animate({width:220},300)}).mouseout(function(){$(this).stop().animate({width:49},300)});if($('.project-carousel').length){$('.project-carousel').owlCarousel({loop:true,margin:25,nav:true,smartSpeed:700,autoplay:5000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:2},800:{items:2},1024:{items:3},1200:{items:4}}});}
if($('.five-item-carousel').length){$('.five-item-carousel').owlCarousel({loop:true,margin:40,nav:true,smartSpeed:700,autoplay:5000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:2,margin:30},800:{items:2,margin:30},1024:{items:3,margin:30},1200:{items:4,margin:30},1400:{items:5,margin:50}}});}
if($('.gallery-carousel').length){$('.gallery-carousel').owlCarousel({loop:true,margin:0,nav:true,smartSpeed:700,autoplay:5000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:2},800:{items:2},1024:{items:3},1200:{items:4},1400:{items:5}}});}
if($('.single-item-carousel').length){$('.single-item-carousel').owlCarousel({loop:true,margin:0,nav:true,smartSpeed:500,autoplay:5000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:1},800:{items:1},1024:{items:1},1200:{items:1}}});}
if($('.four-item-carousel').length){$('.four-item-carousel').owlCarousel({loop:true,margin:0,nav:true,smartSpeed:700,autoplay:4000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},600:{items:1},800:{items:2},1024:{items:2},1200:{items:3},1400:{items:3},1600:{items:4}}});}
if($('.sponsors-carousel').length){$('.sponsors-carousel').owlCarousel({loop:true,margin:0,nav:true,smartSpeed:500,autoplay:4000,navText:['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],responsive:{0:{items:1},480:{items:2},600:{items:3},800:{items:4},1024:{items:5}}});}
if($('#master-slider').length){var sliderMaster=new MasterSlider();sliderMaster.control('arrows');sliderMaster.control('bullets');sliderMaster.control('circletimer',{color:"#FFFFFF",stroke:9});sliderMaster.setup('master-slider',{width:320,height:565,space:0,loop:true,view:'partialWave',layout:'partialview'});}
if($('.price-range-slider').length){$(".price-range-slider").slider({range:true,min:0,max:1000,values:[100,900],slide:function(event,ui){$("input.property-amount").val(ui.values[0]+" - "+ui.values[1]);}});$("input.property-amount").val($(".price-range-slider").slider("values",0)+" - $"+$(".price-range-slider").slider("values",1));}
if($('.lightbox-image').length){$('.lightbox-image').fancybox({openEffect:'fade',closeEffect:'fade',helpers:{media:{}}});}
if($('#contact-form').length){$('#contact-form').validate({rules:{email:{required:true,email:true},username:{required:true},message:{required:true}}});}
if($('.filter-list').length){$('.filter-list').mixItUp({});}
if($('.filter-gallery-one .filter-gallery').length){$(".filter-gallery-one .filter-gallery").mixItUp({selectors:{target:".mix"},layout:{display:"inline-block"},loadmore:{initial:8,loadMore:2,buttonWrapper:".loadmore",buttonClass:"loadmore-button",buttonLabel:"Load More",lessClass:"loadmore-less",lessLabel:"Show Less"}});}
if($('.filter-gallery-two .filter-gallery').length){$(".filter-gallery-two .filter-gallery").mixItUp({selectors:{target:".mix"},layout:{display:"inline-block"},loadmore:{initial:9,loadMore:3,buttonWrapper:".loadmore",buttonClass:"loadmore-button",buttonLabel:"Load More",lessClass:"loadmore-less",lessLabel:"Show Less"}});}
if($('.scroll-to-target').length){$(".scroll-to-target").on('click',function(){var target=$(this).attr('data-target');$('html, body').animate({scrollTop:$(target).offset().top},1500);});}
if($('.wow').length){var wow=new WOW({boxClass:'wow',animateClass:'animated',offset:0,mobile:false,live:true});wow.init();}
$("div.bhoechie-tab-menu>div.list-group>a").click(function(e){e.preventDefault();$(this).siblings('a.active').removeClass("active");$(this).addClass("active");var index=$(this).index();$("div.bhoechie-tab>div.bhoechie-tab-content").removeClass("active");$("div.bhoechie-tab>div.bhoechie-tab-content").eq(index).addClass("active");});$('footer').footerReveal();$(window).on('scroll',function(){headerStyle();});$(window).on('load',function(){handlePreloader();});})(window.jQuery);